chat/urls.py
"""
Chat urls module
"""

from django.urls import path
from django.contrib.auth.decorators import login_required

from .views import Conversations


urlpatterns = [
    path(
        'chats/',
        login_required(Conversations.ChatList.as_view()),
        name='chat-list'),
    path(
        'chat/create/',
        login_required(Conversations.create_chat),
        name='chat-create'),
    path(
        'chat/<int:room_id>/remove/',
        login_required(Conversations.remove_chat),
        name='chat-remove'),
    path(
        'chat/quit/<int:room_id>/',
        login_required(Conversations.quit_room),
        name='chat-quit'),
    path(
        'chat/<int:room_id>/add/<int:friend_id>/',
        login_required(Conversations.add_to_chat),
        name='chat-add-friend'),
    path(
        'chat/<int:room_id>/remove/<int:participant_id>/',
        login_required(Conversations.remove_from_chat),
        name='chat-remove-member'),
    path(
        'chat/<int:room_id>/makeadmin/<int:participant_id>/',
        login_required(Conversations.make_admin),
        name='chat-make-admin'),
    path(
        'chat/<int:room_id>/rmadmin/<int:participant_id>/',
        login_required(Conversations.rm_admin),
        name='chat-rm-admin'),
    path(
        'chat/change_avatar/<int:room_id>/',
        login_required(Conversations.AvatarManaging.as_view()),
        name='chat-avatar-change'),
    path(
        'chat/edit_chat_name/<int:room_id>/',
        login_required(Conversations.edit_chat_name),
        name='chat-edit-name'),
    path(
        'chats/<int:user_id>/<int:friend_id>/',
        login_required(Conversations.chat_move),
        name='chat-friend-redirect'),
    path(
        'chat/go_to_chat/<int:room_id>/',
        login_required(Conversations.Room.as_view()),
        name='chat-go-to-chat'),
    path(
        'chat/go_to_chat/<int:room_id>/get_messages/',
        login_required(Conversations.get_messages),
        name='chat-go-to-chat-get-message'),
    path(
        'chat/go_to_chat/<int:room_id>/send_files/',
        login_required(Conversations.send_files),
        name='chat-go-to-chat-send-files'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('chat.urls')),
    path('', include('index.urls')),
    path('', include('community.urls')),
    path('', include('friends.urls')),
    path('', include('music.urls')),
    path('', include('post.urls')),
    path('', include('user_profile.urls')),
    path('accounts/', include('allauth.urls')),
]


if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns() + static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

meta_social/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('chat.urls')),
    path('', include('index.urls')),
    path('', include('community.urls')),
    path('', include('friends.urls')),
    path('', include('music.urls')),
    path('', include('post.urls')),
    path('', include('user_profile.urls')),
    path('accounts/', include('allauth.urls')),
]


if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns() + static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

post/urls.py
"""
Meta social post urls
"""

from django.urls import path
from django.contrib.auth.decorators import login_required

from community.views import Communities
from .views import PostViews

urlpatterns = [
    path(
        'post/create/',
        login_required(PostViews.post_new),
        name='profile-post-create'),
    path(
        'post/create/<str:community_url>/',
        login_required(Communities.post_community_new),
        name='community-post-create'),

    path(
        'post/<int:post_id>/',
        login_required(PostViews.PostView.as_view()),
        name='post-page'),
    path(
        'post/<int:post_id>/remove/',
        login_required(PostViews.post_remove),
        name='post-remove'),
    path(
        'post/<int:post_id>/send_comment/',
        login_required(PostViews.send_comment),
        name='post-send-comment'),
    path(
        'post/<int:post_id>/edit/',
        login_required(PostViews.PostEdit.as_view()),
        name='post-edit'),
    path(
        'post/<int:post_id>/rt/',
        login_required(PostViews.rt),
        name='post-repost'),

    path(
        'like/<int:post_id>/',
        login_required(PostViews.like_post),
        name='post-like'),
    path(
        'post/<int:post_id>/get_comments/<int:is_all>/',
        login_required(PostViews.get_comments),
        name='post-comments'),
]

post/models.py
"""
Meta social post models
"""

import sys
from io import BytesIO
from PIL import Image

from django.db import models
from django.contrib.auth.models import User
from django.core.files.uploadedfile import InMemoryUploadedFile

from music.models import Music


class Like(models.Model):
    """
    Like model

    :param date: like date
    :param user: like owner
    """
    date = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(to=User, on_delete=models.CASCADE)


class Post(models.Model):
    """
    Post model

    :param user: ForeignKey to :class:`django.contrib.auth.models.User` model. Creator of post
    :param community: ForeignKey to :class:`community.models.Community` model. Creator of post
    :param text: text of post
    :param date: post creation date
    :param likes: ManyToManyField to :class:`post.models.Like`  model
    :param rt: ManyToManyField to :class:`django.contrib.auth.models.User`  model
    :param is_reposted: boolean field
    :param owner: ForeignKey to :class:`django.contrib.auth.models.User` model. Owner of post
    :param owner_community: ForeignKey to :class:`community.models.Community` model. Owner of post
    :param music: ManyToManyField to :class:`music.models.Music` model
    """
    user = models.ForeignKey(to=User, on_delete=models.CASCADE, null=True)
    community = models.ForeignKey(to='community.Community', on_delete=models.CASCADE, null=True)
    text = models.TextField()
    date = models.DateTimeField(auto_now=True, verbose_name='Дата создания')

    likes = models.ManyToManyField(Like, blank=True, related_name='likes')

    rt = models.ManyToManyField(User, blank=True, related_name='rt')

    is_reposted = models.BooleanField(default=False)

    owner = models.ForeignKey(User, on_delete=models.CASCADE, null=True, related_name='owner')
    owner_community = models.ForeignKey(to='community.Community', on_delete=models.CASCADE, null=True, related_name='owner_community')

    music = models.ManyToManyField(Music)

    class Meta:
        """
        Class storing information for admin interface
        """
        verbose_name = 'Посты'
        verbose_name_plural = 'Посты'

    def __str__(self):
        """
        Returns a string representation of an object

        :return: text of post
        :rtype: str
        """
        return self.text

    def get_owner(self):
        """
        Returns owner of post

        :return: owner of post
        :rtype: :class:`community.models.Community` or :class:`user_profile.models.Profile`
        """
        return self.community if self.community else self.user.profile

    def get_owner_name(self):
        """
        Returns owner name

        :rtype: str
        """
        if self.community:
            return self.community.name
        return self.user.profile.get_name()

    def get_link(self):
        """
        Returns owner link

        :rtype: str
        """
        if self.community:
            return '/community/' + str(self.community.custom_url) + '/'
        return '/accounts/profile/' + str(self.user.profile.custom_url) + '/'

    def get_images(self):
        """
        Returns images of post

        :rtype: django queryset
        """
        return PostImages.objects.filter(post=self).order_by('order')

    def get_images_count(self):
        """
        Returns the number of post images

        :rtype: int
        """
        return PostImages.objects.filter(post=self).count()

    def comments(self):
        """
        Returns all comments of post

        :rtype: django queryset
        """
        return Comment.objects.filter(post=self)

    def amount_of_comments(self):
        """
        Returns the number of post comments

        :rtype: int
        """
        return len(self.comments())

    def get_editors(self):
        """
        Returns all users, who can edit or delete post

        :rtype: :class:`django.contrib.auth.models.User`
        """
        editors = []
        if self.user:
            editors.append(self.user)
        if self.community:
            editors += self.community.admins.all()
        return editors

    def get_rt_count(self):
        """
        Returns amount of rts

        :rtype: int
        """
        return len(self.rt.all())


class PostImages(models.Model):
    """
    Posts images model

    :param post: ForeignKey to :class:`post.models.Post`
    :param from_user: ForeignKey to :class:`django.contrib.auth.models.User`
    :param image: ImageField
    :param order: order of image in post
    """
    post = models.ForeignKey(Post, models.CASCADE)
    from_user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    image = models.ImageField(upload_to='post/images/', blank=True, null=True)
    order = models.IntegerField(default=0)

    def save(self):
        """
        Resize and compress image before save
        """
        img = Image.open(self.image)
        output = BytesIO()

        new_size = (720, (img.size[1] * 720) // img.size[0])

        img = img.resize(new_size, Image.ANTIALIAS)

        try:
            img.save(output, format='JPEG', quality=60)
            output.seek(0)
            self.image = InMemoryUploadedFile(output, 'ImageField', "{}.jpg".format(self.image.name.split('.')[0]), 'image/jpeg', sys.getsizeof(output), None)
        except OSError:
            img.save(output, format='PNG', quality=60)
            output.seek(0)
            self.image = InMemoryUploadedFile(output, 'ImageField', "{}.png".format(self.image.name.split('.')[0]), 'image/png', sys.getsizeof(output), None)

        super(PostImages, self).save()


class Comment(models.Model):
    """
    Post comments model

    :param date: comment creation date
    :param text: text of comment
    :param post: ForeignKey to :class:`post.models.Post`
    :param user: ForeignKey to :class:`django.contrib.auth.models.User`
    """
    date = models.DateTimeField(auto_now=True, verbose_name='Дата')
    text = models.CharField(max_length=500, verbose_name='Текст')

    post = models.ForeignKey(to=Post, on_delete=models.CASCADE)
    user = models.ForeignKey(to=User, on_delete=models.CASCADE)

    class Meta:
        """
        Class storing information for admin interface
        """
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарий'

post/forms.py
"""
Meta social post forms
"""

from django import forms

from .models import Post, PostImages
from .widgets import MyImageFieldWidget


class PostForm(forms.ModelForm):
    """
    Form for creation post

    :param text: text of post
    :param music: contains music ids
    """
    text = forms.CharField(max_length=500)
    music = forms.CharField(required=False, widget=forms.TextInput(attrs={'style': 'display: none;'}))

    class Meta:
        model = Post
        fields = ('text',)

    def __init__(self, *args, **kwargs):
        super(PostForm, self).__init__(*args, **kwargs)
        self.fields['text'].label = ''
        self.fields['music'].label = ''
        self.fields['text'].widget = forms.Textarea()
        self.fields['text'].widget.attrs['width'] = '100%'
        self.fields['text'].widget.attrs['class'] = 'form-control md-textarea'
        self.fields['text'].widget.attrs['rows'] = '1'
        self.fields['text'].widget.attrs['placeholder'] = 'Поделитель своими новостями...'
        self.fields['text'].widget.attrs['style'] = 'resize: none; padding: 0px 2px;'


class PostImageForm(forms.ModelForm):
    """
    Form for adding images to post

    :param image: image of post
    """
    image = forms.ImageField()

    class Meta:
        model = PostImages
        fields = ('image',)

    def __init__(self, *args, **kwargs):
        super(PostImageForm, self).__init__(*args, **kwargs)
        self.fields['image'].label = ''


class EditPostImageForm(forms.ModelForm):
    """
    Form for editing images of post

    :param image: image of post
    """
    image = forms.ImageField(required=False, widget=MyImageFieldWidget)

    class Meta:
        model = PostImages
        fields = ('image',)

    def __init__(self, *args, **kwargs):
        super(EditPostImageForm, self).__init__(*args, **kwargs)
        self.fields['image'].label = ''

post/templates/post/comments.html
{% if all %}
    {% for comment in post.comments %}
        <div class="media">
            <img src="{{ comment.user.profile.image.url }}" class="mr-2 mt-2 rounded-circle border" width=40 height=40>
            <div class="media-body">
                <h6 class="mt-2 mb-0">
                    <a href="/accounts/profile/{{ comment.user.profile.custom_url }}/">{{ comment.user.profile.get_name }}</a>
                    <small>{{ comment.date }}</small>
                </h6>
                <p class="mb-0">
                    {{ comment.text }}
                </p>
            </div>
        </div>
        {% if not forloop.last %}
            <hr class="mt-1 mb-0">
        {% endif %}
    {% endfor %}
{% else %}
    {% for comment in post.comments|slice:":1" %}
        <div class="media">
            <img src="{{ comment.user.profile.image.url }}" class="mr-2 mt-2 rounded-circle border" width=40 height=40>
            <div class="media-body">
                <h6 class="mt-2 mb-0">
                    <a href="/accounts/profile/{{ comment.user.profile.custom_url }}/">{{ comment.user.profile.get_name }}</a>
                    <small>{{ comment.date }}</small>
                </h6>
                <p class="mb-0">
                    {{ comment.text }}
                </p>
            </div>
        </div>
        {% if not forloop.last %}
            <hr class="mt-1 mb-0">
        {% endif %}
    {% endfor %}
{% endif %}

post/templates/post/full_post.html
{% extends 'base_menu.html' %}

{% block center %}
    {% include 'post/post.html' %}
{% endblock center %}

{% block extra__js %}

{% endblock extra__js %}

post/templates/post/post.html
<div class="card mb-3 text-left post-item">
    <div class="card-body pb-0 mb-0">
        <div class="post-author">
            <img src="{{ post.get_owner.image.url }}" class="rounded-circle border float-left" width="40" height="40">

            <div class="name-date float-left ml-2 mb-0 pb-0">
                <a href="{{ post.get_link }}">
                    {{ post.get_owner_name }} <small class="text-muted">поделился(-ась) записью {% if post.is_reposted %}
                                                                                                    {% if post.owner %}
                                                                                                        (<a href="/accounts/profile/{{ post.owner.profile.custom_url }}/">{{ post.owner.profile.get_name }}</a>)
                                                                                                    {% else %}
                                                                                                        (<a href="/community/{{ post.owner_community.custom_url }}/">{{ post.owner_community.name }}</a>)
                                                                                                    {% endif %}
                                                                                                {% endif %}</small>
                </a>
                <p style="margin-top: -5px;">
                    <small class="text-muted">{{ post.date }}</small>
                </p>
            </div>

            <div class="post-edit float-right">
                <button class="btn btn-outline-primary btn-sm px-1 py-0 my-0 mr-0 rounded-pill" style="font-size: 12pt;" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <i class="fa fa-ellipsis-h" aria-hidden="true"></i>
                </button>

                <div class="dropdown-menu dropdown-menu-right">
                    <a class="dropdown-item" href="/post/{{ post.id }}/">Перейти к посту</a>
                    {% if user in post.get_editors %}
                        <a class="dropdown-item" onclick="remove_post(event, '/post/{{ post.id }}/remove/')">Удалить</a>
                        <a class="dropdown-item" href="/post/{{ post.id }}/edit/">Редактировать</a>
                    {% endif %}
                </div>
            </div>
        </div>
        
        <br style="clear: both;">

        <p style="white-space: pre-wrap">{{ post.text }}</p>

        {% if post.music.count %}
            <div class="post-music mb-2">
                {% for music in post.music.all %}
                    <div>
                        {% if music in user.profile.playlist.all %}
                            <button class="btn btn-sm btn-outline-success ml-0" onclick="addMusicToPlaylist('/music/{{ music.id }}/add/')" disabled>+</button>
                        {% else %}
                            <button class="btn btn-sm btn-outline-success ml-0" onclick="addMusicToPlaylist('/music/{{ music.id }}/add/')">+</button>
                        {% endif %}
                        <span>{{ music.artist }} - {{ music.title }}</span>
                    </div>
                {% endfor %}
            </div>
        {% endif %}

        {% if post.get_images %}
            <div class="post-images masonry-grid mt-2">
                {% for post_img in post.get_images %}
                    {% if forloop.first %}
                        <a data-fancybox="photo" href="{{ post_img.image.url }}" class="masonry-grid-item masonry-grid-item--width2 mx-1 {% if post.get_images.count == 1 %}w-100{% endif %}">
                            <img src="{{ post_img.image.url }}" width="100%" class="mb-1">
                        </a>
                    {% else %}
                        <a data-fancybox="photo" href="{{ post_img.image.url }}" class="masonry-grid-item mx-1">
                            <img src="{{ post_img.image.url }}" width="100%" class="mb-1">
                        </a>
                    {% endif %}
                {% endfor %}
            </div>
            <hr class="my-1">
        {% endif %}

        <div class="post-manage">
            {% if post in user.profile.liked_posts.all %}
                <a name="like" class="text-danger" onclick="likePost(event, '{{ post.id }}')">
                    <span class="like-counter">{{ post.likes.count }}</span>
                    <i class="fa fa-heart" aria-hidden="true"></i>
                </a>
            {% else %}
                <a name="like" class="text-muted" onclick="likePost(event, '{{ post.id }}')">
                    <span class="like-counter">{{ post.likes.count }}</span>
                    <i class="fa fa-heart" aria-hidden="true"></i>
                </a>
            {% endif %}
            <a name="comment" class="text-muted mb-0 ml-2" onclick="showComments(event, '{{ post.id }}')" js-data="1">
                <span class="comment-counter">{{ post.amount_of_comments }}</span>
                <i class="far fa-comment"></i>
            </a>
            {% if c_user != user %}
                <a href="/post/{{ post.id }}/rt/" class="text-muted mb-0 ml-2">
                    <span class="repost-counter">{{ post.get_rt_count }}</span>
                    <i class="fa fa-bullhorn" aria-hidden="true"></i>
                </a>
            {% endif %}
        </div>

        <div class="post-send-comment border-top mt-1 mb-0 pb-0">
            <form onsubmit="return sendCommentInd(event)" method="POST" class="md-form input-group mt-2 mb-2">
                {% csrf_token %}
                <input type="hidden" name="post_id" value="{{ post.id }}">
                <input type="text" class="form-control comment-input" name='text' placeholder="Оставить комментарий...">
                <div class="input-group-append">
                    <button class="btn btn-md btn-outline-primary m-0 px-3" type="submit">
                        <i class="fa fa-paper-plane" aria-hidden="true"></i>
                    </button>
                </div>
            </form>
        </div>
    </div>

    {% if post.comments %}
        <div class="card-footer post-comments pt-1">
            {% include 'post/comments.html' %}
        </div>
    {% endif %}
</div>

post/templates/post/post_menu.html
<style>
    #drop-area.highlight {
        border: 2px dashed black;
    }

    .my-form {
        margin-bottom: 10px;
    }

    #gallery {
        margin-top: 10px;
        margin-left: 2px;
    }

    #gallery img {
        width: 100%;
        height: 100%;
        display: block;
        vertical-align: middle;
    }

    #fileElem {
        display: none;
    }

    .img-div {
        position: relative;
        display: inline-block;
        height: 45px;
        width: calc(10% - 3px);
        margin-right: 5px;
    }

    .post-image-badge {
        position: absolute;
        top: -7px;
        right: -7px;
        color: white;
        border-radius: 50%;
        background-color: #ff4444;
        width: 23px;
        height: 23px;
        z-index: 99;
        border: 1px solid white;
    }

    .post-image-badge:hover {
        cursor: pointer;
        background-color: #F13636;
    }

    .post-image-badge:active {
        background-color: #CC0000;
    }
</style>

<div id="drop-area" class="card">
    <div class="card-body text-left">
        <form method="POST" action="{{ action_type }}" enctype="multipart/form-data" class="post-form">
            {% csrf_token %}

            <div class="md-form input-group">
                <div class="input-group-prepend">
                    <button class="btn btn-outline-primary btn-sm py-0 my-0" type="button" style="font-size: 12pt;" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="fa fa-paperclip" aria-hidden="true"></i>
                    </button>
                    <div class="dropdown-menu">
                        <a class="dropdown-item" onclick="triggerInput()">Изображения</a>
                        <a class="dropdown-item" data-toggle="modal" data-target="#musicSelectModal">Музыка</a>
                    </div>
                </div>
                {{ postform }}
                <div class="input-group-append">
                    <button class="btn btn-outline-primary btn-sm py-0 my-0" type="submit" style="font-size: 12pt;">
                        <i class="fa fa-paper-plane" aria-hidden="true"></i>
                    </button>
                </div>
            </div>

            <input type="file" id="fileElem" multiple accept="image/*" onchange="handleFiles(this.files)">
            <div id="gallery"></div>

            {{ formset.management_form }}
            <div style="display: none;">
                {% for form in formset %}
                    {{ form }} <br>
                {% endfor %}
            </div>
        </form>
    </div>
</div>

<div class="modal modal fade" id="musicSelectModal" tabindex="-1" role="dialog" aria-labelledby="musicSelectModal" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Выберите музыку:</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body" id="select-music-list">
                {% for pos in user.profile.get_music_list %}
                    <div>
                        <button class="btn btn-sm btn-primary" onclick="addMusic(event, {{ pos.position.id }}, '{{ pos.position.artist }} - {{ pos.position.title }}')">+</button>
                        <span style="max-width: 400px;" class="text-truncate">{{ pos.position.artist }} - {{ pos.position.title }}</span>
                    </div>
                {% empty %}
                    У вас нет музыки
                {% endfor %}
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary btn-block" data-dismiss="modal">Закрыть</button>
            </div>
        </div>
    </div>
</div>

<script>
    function removeMusic(e) {
        let div = document.createElement('div')

        let btn = document.createElement('button')
        btn.classList.add('btn')
        btn.classList.add('btn-sm')
        btn.classList.add('btn-primary')
        btn.innerHTML = '+'
        btn.onclick = function () {
            addMusic(event, $(e.target).attr('music-id'), $(e.target).attr('music-name'))
        }

        let span = document.createElement('span')
        span.classList.add('text-truncate')
        $(span).attr('width', '400px')
        span.innerHTML = $(e.target).attr('music-name')

        div.appendChild(btn)
        div.appendChild(span)

        $('#select-music-list')[0].appendChild(div)
        
        let vals = $('#id_music')[0].value.split(' ')
        for (let i=0; i < vals.length; i++) {
            if (vals[i] == $(e.target).attr('music-id')) {
                vals.splice(i, 1)
            }
        }

        let new_val = ''
        for (let i=0; i < vals.length; i++) {
            new_val += vals[i]
        }

        $('#id_music').val(new_val)

        e.target.parentNode.remove()
    }

    function getMusicCount() {
        return $('#id_music')[0].value.split(' ').length
    }

    function addMusic(e, id, name) {
        if (getMusicCount() == 10) {
            alert('Максимум 10 песен')
            return
        }

        $('#id_music')[0].value += id + ' '

        let imgDiv = document.createElement('div')
        imgDiv.classList.add('img-div')
        imgDiv.classList.add('border')

        let nameP = document.createElement('p')
        nameP.classList.add('text-truncate')
        nameP.innerHTML = name

        let rmBtn = document.createElement('span')
        rmBtn.classList.add('post-image-badge');
        rmBtn.classList.add('text-center');
        rmBtn.onclick = removeMusic;
        rmBtn.innerHTML = 'X';
        $(rmBtn).attr('music-name', name)
        $(rmBtn).attr('music-id', id)

        imgDiv.appendChild(nameP)
        imgDiv.appendChild(rmBtn)

        document.getElementById('gallery').appendChild(imgDiv)

        e.target.parentNode.remove()
    }

    autosize(document.getElementById("id_text"));

    function triggerInput() {
        $('#fileElem')[0].click()
    }

    let dropArea = document.getElementById('drop-area')

    ;['dragenter', 'dragover', 'dragleave', 'drop'].forEach(eventName => {
        dropArea.addEventListener(eventName, preventDefaults, false);
    });

    function preventDefaults(e) {
        e.preventDefault();
        e.stopPropagation()
    }

    ;['dragenter', 'dragover'].forEach(eventName => {
        dropArea.addEventListener(eventName, highlight, false)
    })

    ;['dragleave', 'drop'].forEach(eventName => {
        dropArea.addEventListener(eventName, unhighlight, false)
    });

    function highlight(e) {
        dropArea.classList.add('highlight')
    }

    function unhighlight(e) {
        dropArea.classList.remove('highlight')
    }

    dropArea.addEventListener('drop', handleDrop, false);

    function handleDrop(e) {
        let dt = e.dataTransfer;
        let files = dt.files;

        handleFiles(files)
    }

    function handleFiles(files) {
        files = [...files];
        files.forEach(uploadFile)
    }

    function get_free_inputs() {
        let inputs = [];
        for (var i = 0; i < 10; i++) {
            let input = document.getElementById("id_form-" + i + "-image");
            if (!input.value) {
                inputs.push(input)
            }
        }
        return inputs
    }

    function uploadFile(file) {
        let inputs = get_free_inputs();
        
        if (inputs.length == 0) {
            alert('Нельзя загрузить более 10 картинок');
            return
        }

        const dT = new DataTransfer();
        dT.items.add(file);
        inputs[0].files = dT.files;

        let input_id = inputs[0].id[8];

        previewFile(file, input_id)
    }

    function removeFile(e) {
        let current_id = e.target.id[e.target.id.length - 1];

        document.getElementById("id_form-" + current_id + "-image").value = '';
        e.target.parentNode.remove()
    }

    function previewFile(file, input_id) {
        let reader = new FileReader();
        reader.readAsDataURL(file);
        reader.onloadend = function () {
            let imgDiv = document.createElement('div')
            imgDiv.classList.add('img-div')

            let img = document.createElement('img');
            img.src = reader.result;

            let rmBtn = document.createElement('span')

            rmBtn.id = "image_preview-" + input_id;
            rmBtn.classList.add('post-image-badge');
            rmBtn.classList.add('text-center');
            rmBtn.onclick = removeFile;
            rmBtn.innerHTML = 'X';

            imgDiv.appendChild(img)
            imgDiv.appendChild(rmBtn)

            document.getElementById('gallery').appendChild(imgDiv)
        }
    }
</script>